# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 3306
  username: root
  password: rootroot
  socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
  database: sismologia_development

test:
  <<: *default
  database: sismologia_test

production:
  <<: *default
  database: sismologia_production
  username: sismologia
  password: <%= ENV['SISMOLOGIA_DATABASE_PASSWORD'] %>
