default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 3306
  username: root
  password: rootroot
  socket: /opt/lampp/var/mysql/mysql.sock

development:
  <<: *default
  database: crud_ruby_dev
  
test:
  <<: *default
  database: crud_ruby_test

production:
  <<: *default
  database: crud_ruby
  username: root
  password: rootroot
  # password: <%= ENV['CRUD_DATABASE_PASSWORD'] %>
